# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bunnicula}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nathan Stults"]
  s.date = %q{2010-07-09}
  s.default_executable = %q{bunnicula}
  s.description = %q{A very simple relay for moving messages from a local broker to a remote broker}
  s.email = %q{hereiam@sonic.net}
  s.executables = ["bunnicula"]
  s.extra_rdoc_files = [
    "LICENSE.txt"
  ]
  s.files = [
    "LICENSE.txt",
     "README",
     "Rakefile",
     "Relayfile",
     "bin/bunnicula",
     "bunnicula.gemspec",
     "config/arguments.rb",
     "config/boot.rb",
     "config/environment.rb",
     "config/environments/development.rb",
     "config/environments/production.rb",
     "config/environments/test.rb",
     "config/post-daemonize/readme",
     "config/pre-daemonize/bunnicula.rb",
     "config/pre-daemonize/readme",
     "lib/bunnicula.rb",
     "lib/bunnicula/amqp.rb",
     "lib/bunnicula/bunny_farm.rb",
     "lib/bunnicula/dsl_base.rb",
     "lib/bunnicula/exchange.rb",
     "lib/bunnicula/rabbit.rb",
     "lib/bunnicula/relay.rb",
     "lib/bunnicula/support.rb",
     "lib/bunnicula/vampire_rabbit.rb",
     "lib/bunnicula/version.rb",
     "libexec/bunnicula-daemon.rb",
     "test/config/Relayfile.rb",
     "test/lib/bunnicula_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/PlasticLizard/bunnicula}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A very simple relay for moving messages from a local broker to a remote broker}
  s.test_files = [
    "test/config/Relayfile.rb",
     "test/lib/bunnicula_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<daemon-kit>, ["= 0.1.7.12"])
      s.add_runtime_dependency(%q<bunny>, ["= 0.6.0"])
      s.add_runtime_dependency(%q<amqp>, ["= 0.6.7"])
      s.add_development_dependency(%q<shoulda>, ["= 2.11.1"])
    else
      s.add_dependency(%q<daemon-kit>, ["= 0.1.7.12"])
      s.add_dependency(%q<bunny>, ["= 0.6.0"])
      s.add_dependency(%q<amqp>, ["= 0.6.7"])
      s.add_dependency(%q<shoulda>, ["= 2.11.1"])
    end
  else
    s.add_dependency(%q<daemon-kit>, ["= 0.1.7.12"])
    s.add_dependency(%q<bunny>, ["= 0.6.0"])
    s.add_dependency(%q<amqp>, ["= 0.6.7"])
    s.add_dependency(%q<shoulda>, ["= 2.11.1"])
  end
end

